### ISSUE TITLE
 Definir novos métodos para o classificador

### ISSUE THREAD

**Issue by AbnerErnaniADSFatec** [ProjetoIntegradorADSFatec/python-cnn#20]
Com a avaliação dos resultados obtidos definir novos métodos ou continuar com os mesmos dependendo do resultado para o processamento das imagens.

**Comment by GomesDosSantos** [comment]
Como recomendado pelos especialistas da Visiona. Este é uma breve apresentação (estilo medium) sobre o UNet (*simetria em segmentação*).     
https://towardsdatascience.com/u-net-b229b32b4a71
